# Generated by Django 5.1.7 on 2025-03-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcheck',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailcheck',
            name='domain_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcheck',
            name='domain_organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailcheck',
            name='domain_popularity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcheck',
            name='domain_reputation',
            field=models.CharField(blank=True, default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='emailcheck',
            name='domain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcheck',
            name='domain_website',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
