# Generated by Django 5.1.7 on 2025-03-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_emailcheck_domain_emailcheck_domain_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcheck',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='emailcheck',
            name='domain_creation_date',
        ),
        migrations.RemoveField(
            model_name='emailcheck',
            name='domain_organization',
        ),
        migrations.RemoveField(
            model_name='emailcheck',
            name='domain_popularity_score',
        ),
        migrations.RemoveField(
            model_name='emailcheck',
            name='domain_reputation',
        ),
        migrations.RemoveField(
            model_name='emailcheck',
            name='domain_verified',
        ),
        migrations.RemoveField(
            model_name='emailcheck',
            name='domain_website',
        ),
    ]
