# Generated by Django 5.1.7 on 2025-03-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_emailcheck_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposableDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=1.0)),
            ],
        ),
    ]
