# Generated by Django 5.1.7 on 2025-03-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_spamdomain_spamemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpamDomain',
        ),
        migrations.DeleteModel(
            name='SpamEmail',
        ),
    ]
