# Generated by Django 5.1.7 on 2025-03-16 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_delete_spamdomain_delete_spamemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamDatabaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('is_domain', models.BooleanField(default=True)),
                ('blacklists', models.JSONField(default=list)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
    ]
