# Generated by Django 5.1.7 on 2025-04-26 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_feedback_email_feedback_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('final_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_malicious', models.BooleanField(default=False)),
                ('has_ssl', models.BooleanField(default=False)),
                ('is_shortened', models.BooleanField(default=False)),
                ('domain', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_name', models.CharField(max_length=255)),
                ('tracker_type', models.CharField(max_length=100)),
                ('script_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('url_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='services.urlcheck')),
            ],
        ),
        migrations.CreateModel(
            name='URLCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_rating', models.IntegerField(default=0)),
                ('ssl_info', models.JSONField(blank=True, null=True)),
                ('domain_age_days', models.IntegerField(blank=True, null=True)),
                ('domain_info', models.JSONField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('warnings', models.JSONField(default=list)),
                ('url_check', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='services.urlcheck')),
            ],
        ),
        migrations.CreateModel(
            name='URLRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('redirect_url', models.URLField(max_length=2000)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('url_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='services.urlcheck')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
