# Generated by Django 5.1.7 on 2025-04-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_urlcheck_trackerdetection_urlcheckresult_urlredirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcheckresult',
            name='is_shortlink',
            field=models.BooleanField(default=False),
        ),
    ]
