# Generated by Django 5.1.7 on 2025-04-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_urlcheckresult_is_shortlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlcheckresult',
            name='is_shortlink',
        ),
    ]
