# Generated by Django 5.1.7 on 2025-05-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_urlcheckresult_is_shortlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcheckresult',
            name='embedded_objects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='urlcheckresult',
            name='iframes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='urlcheckresult',
            name='links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='urlcheckresult',
            name='scripts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='urlcheckresult',
            name='server_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
