# Generated by Django 5.1.7 on 2025-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_urlcheckresult_is_shortlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcheckresult',
            name='ip_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
