# Generated by Django 5.1.7 on 2025-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_urlcheckresult_ip_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcheckresult',
            name='discovered_content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urlcheckresult',
            name='hosting_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
