# Generated by Django 5.1.7 on 2025-05-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_urlcheckresult_embedded_objects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlcheckresult',
            name='embedded_objects',
        ),
        migrations.RemoveField(
            model_name='urlcheckresult',
            name='iframes',
        ),
        migrations.RemoveField(
            model_name='urlcheckresult',
            name='links',
        ),
        migrations.RemoveField(
            model_name='urlcheckresult',
            name='scripts',
        ),
        migrations.AlterField(
            model_name='urlcheckresult',
            name='server_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
