# Generated by Django 5.1.7 on 2025-05-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_urlcheckresult_embedded_objects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlcheckresult',
            name='server_info',
        ),
    ]
