# Generated by Django 5.1.7 on 2025-05-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_urlcheckresult_server_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcheckresult',
            name='hosting_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urlcheckresult',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='urlcheckresult',
            name='ip_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urlcheckresult',
            name='server_software',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
