# Generated by Django 5.1.7 on 2025-05-06 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_urlcheckresult_hosting_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcheck',
            name='scan_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='urlcheck',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
