# Generated by Django 5.1.7 on 2025-05-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_urlcheckresult_discovered_content_and_more'),
        ('services', '0018_urlcheck_scan_date_urlcheck_status'),
    ]

    operations = [
    ]
