# Generated by Django 5.1.7 on 2025-05-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_merge_20250506_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlcheck',
            name='scan_date',
        ),
        migrations.RemoveField(
            model_name='urlcheck',
            name='status',
        ),
        migrations.RemoveField(
            model_name='urlcheckresult',
            name='hosting_provider',
        ),
        migrations.RemoveField(
            model_name='urlcheckresult',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='urlcheckresult',
            name='ip_range',
        ),
        migrations.RemoveField(
            model_name='urlcheckresult',
            name='server_software',
        ),
    ]
