# Generated by Django 5.1.7 on 2025-05-06 19:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_urlcheck_scan_date_remove_urlcheck_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=255)),
                ('detected_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('is_malicious', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_id', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_rating', models.IntegerField(default=0)),
                ('is_malicious', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('warnings', models.JSONField(default=list)),
                ('hash_md5', models.CharField(blank=True, max_length=32, null=True)),
                ('hash_sha1', models.CharField(blank=True, max_length=40, null=True)),
                ('hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('file_check', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='services.filecheck')),
            ],
        ),
        migrations.CreateModel(
            name='FileScanMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(default=dict)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('modification_time', models.DateTimeField(blank=True, null=True)),
                ('access_time', models.DateTimeField(blank=True, null=True)),
                ('file_check', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='services.filecheck')),
            ],
        ),
    ]
