# Generated by Django 5.1.7 on 2025-03-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_failed_attempts_otp_locked_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='feedback',
        ),
    ]
